AWSTemplateFormatVersion: '2010-09-09'
Description: |
  Esta plantilla crea un grupo de seguridad con los puertos 22 y 80.
  También crea una instancia EC2 con la AMI de Ubuntu Server 22.04 y le asocia el grupo de seguridad.
  A la instancia se le instala apache y se crea un archivo de bienvenida en /var/www/html/index.html.
Resources:
  MySecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sg_webserver_cloudformation
      GroupDescription: Grupo de seguridad WebServer CloudFormation
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
  MyEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-06878d265978313ca
      InstanceType: t2.small
      SecurityGroups:
        - !Ref MySecurityGroup
      KeyName: talentotech2024
      Tags:
        - Key: Name
          Value: instancia-webserver
      UserData: !Base64 |
        #!/bin/bash
        sudo apt-get update
        sudo apt-get install -y apache2
        sudo systemctl start apache2
        sudo systemctl enable apache2
        echo "<h1>Bienvenido a la instancia de EC2: $(hostname -f) </h1>" | sudo tee /var/www/html/index.html
  MyRDS:
    Type: AWS::RDS::DBInstance
    Properties:
      DBName: db_talentotech
      Engine: postgres
      DBInstanceClass: db.t3.micro
      AllocatedStorage: "5"
      MultiAZ: false
      PubliclyAccessible: true
      MasterUsername: admintalentotech
      MasterUserPassword: password123
  MySecurityGroupRDS:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: sg_rds_cloudformation
      GroupDescription: Grupo de seguridad RDS CloudFormation
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 5432
          ToPort: 5432
          SourceSecurityGroupName: !Ref MySecurityGroup

Outputs:
  WebAppDatabaseEndpoint:
    Description: "Connection endpoint for the database"
    Value: !GetAtt MyRDS.Endpoint.Address